### ISSUE TITLE
Error converting.. Maybe I'm just dumb

### ISSUE THREAD

**Issue by Greger420** [10se1ucgo/pyjam#13]
17:05:47 CRITICAL: FFmpeg converter: Couldn't convert /home/retard/Desktop/PyJam/downloads/I'm lookin like money.webm
17:05:47 CRITICAL: FFmpeg converter: Error output log
/usr/bin/ffmpeg: /tmp/_MEINyjdKP/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /usr/lib/x86_64-linux-gnu/libjack.so.0)
/usr/bin/ffmpeg: /tmp/_MEINyjdKP/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /usr/lib/x86_64-linux-gnu/libzmq.so.5)
/usr/bin/ffmpeg: /tmp/_MEINyjdKP/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /usr/lib/x86_64-linux-gnu/libopencv_core.so.2.4)
/usr/bin/ffmpeg: /tmp/_MEINyjdKP/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /usr/lib/x86_64-linux-gnu/libopencv_imgproc.so.2.4)
/usr/bin/ffmpeg: /tmp/_MEINyjdKP/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /usr/lib/x86_64-linux-gnu/libsnappy.so.1)
/usr/bin/ffmpeg: /tmp/_MEINyjdKP/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /usr/lib/x86_64-linux-gnu/libtbb.so.2)

17:05:50 CRITICAL: Error converting these files
/home/retard/Desktop/PyJam/downloads/I'm lookin like money.webm
17:05:50 INFO: Songs converted with 1 error(s)
17:05:51 INFO: Generating track list with path audio/csgo

**Comment by sKuhLight** [comment]
For me converting with Pyjam isn't working, too. Converty it manually via audacity. 
Look for HLDJ Audio Convert Tutorials. Most of them are with audacity and should work with pyjam.
Or take csgoMP(csgoMusicPlayer). The Build-In converter there is working for me .-.

**Comment by Greger420** [comment]
Ty dude csgoMP worked for me
