### ISSUE TITLE
GUI bug on OSX

### ISSUE THREAD

**Issue by gabsens** [10se1ucgo/pyjam#3]
After adding a song in the program, left-clicking on the line it has in the GUI produces an error.

> An error has occured!
> 
> Traceback (most recent call last):
>   File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/ObjectListView/ObjectListView.py", line 1668, in _HandleLeftDown
>     (row, flags, subitem) = self.HitTestSubItem(evt.GetPosition())
>   File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/ObjectListView/ObjectListView.py", line 1362, in HitTestSubItem
>     if (scrolledX - left) < self.smallImageList.GetSize(0)[0]:
> AttributeError: 'NoneType' object has no attribute 'GetSize'

After closing the error message, pyjam still works fine.

INFORMATION:
- OSX 10.10.5
- pyjam1.2.3
- 64-bit

**LOG:**

```21:46:01 CRITICAL: Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/ObjectListView/ObjectListView.py", line 1668, in _HandleLeftDown
    (row, flags, subitem) = self.HitTestSubItem(evt.GetPosition())
  File "/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/ObjectListView/ObjectListView.py", line 1362, in HitTestSubItem
    if (scrolledX - left) < self.smallImageList.GetSize(0)[0]:
AttributeError: 'NoneType' object has no attribute 'GetSize'

```
```

**Comment by 10se1ucgo** [comment]
Yeah, this is an error with ObjectListView (the ListCtrl widget wrapper). I had that on Linux as well. I'm not exactly sure as to WHY, but I'll have to look into it.

**Comment by 10se1ucgo** [comment]
I'll likely fork OLV, patch it and put it in GitHub.

**Comment by 10se1ucgo** [comment]
Do not ask why this worked. I do not know why this worked. OLV must be broken, or something.
