### ISSUE TITLE
Clearing one bind clears all the binds (OSX)

### ISSUE THREAD

**Issue by gabsens** [10se1ucgo/pyjam#4]
When left-clicking on a song and pressing "Clear bind" to delete this specific bind, all the other binds dedicated to the other songs are cleared as well.

**Comment by 10se1ucgo** [comment]
This may be a visual bug (again, OLV bug if so). Can you check the `track_data.json` file for me and check if the binds are there? If not, I'll look into it.

**Comment by 10se1ucgo** [comment]
To clarify: `track_data.json` should be in your game's audio folder.

**Comment by gabsens** [comment]
Before I clear anything

> {"The Cyka Blyat Song ": {"bind": "-"}, "boostmeister": {"bind": ","}, "rushb": {"bind": "."}, "tec9meister": {"bind": "["}}

After I clear one of the  songs

> {"The Cyka Blyat Song ": {}, "boostmeister": {}, "rushb": {}, "tec9meister": {"bind": ""}}

**Comment by 10se1ucgo** [comment]
I might know the problem, I'll try to fix it when I get home.

**Comment by 10se1ucgo** [comment]
Okay, I think I fixed it in 54c25f0

**Comment by gabsens** [comment]
It works, thanks.
