### ISSUE TITLE
Can't use it

### ISSUE THREAD

**Issue by lamka02sk** [10se1ucgo/pyjam#8]
Hi, I am using Ubuntu 16.04, but it does not work.
When I add CSGO, it still says Starting and nothing happens. Also I cant add music

Some error informations:
An error has occured!

Traceback (most recent call last):
  File "<string>", line 167, in start_stop
  File "jam_tools.py", line 240, in start
  File "watchdog/observers/api.py", line 255, in start
  File "watchdog/utils/**init**.py", line 111, in start
  File "watchdog/observers/inotify.py", line 121, in on_thread_start
  File "watchdog/observers/inotify_buffer.py", line 35, in **init**
  File "watchdog/observers/inotify_c.py", line 187, in **init**
  File "watchdog/observers/inotify_c.py", line 363, in _add_dir_watch
OSError: Path is not a directory

Even when sometimes it starts it dont show any music

**Comment by 10se1ucgo** [comment]
Hi, what version of wxPython are you using?

**Comment by 10se1ucgo** [comment]
Oh, oops, I didn't see the modified issue. Not at home right now, I'll take a look as soon as I get home.

**Comment by lamka02sk** [comment]
Some problems are now solved, but still cant realise why no tracks showing. Tried different folders and formats (*.aac, *.mp3) and still nothing.

**Comment by 10se1ucgo** [comment]
You have to use the audio converter. Source engine audio codec has very specific audio settings required.

**Comment by lamka02sk** [comment]
Windows: Oh, thank you, I thought I can use any mp3 :) Can you tell me exactly what type of mp3 is needed?
- now tried again on Linux and conversion ends with error.

**Comment by 10se1ucgo** [comment]
Not mp3, wav.
- 22050Hz for CS:GO, 11025Hz for everything else. 
- Mono
- PCM 16-bit little endian
- Make sure the file has no metadata.

**Comment by 10se1ucgo** [comment]
What error are you getting? Output is logged to `pyjam.log`.

**Comment by lamka02sk** [comment]
On screen I get this error (file downloaded with pyjam audio downloader):
`The following files caused errors
/media/xxx/xxx/xxx/Steve Void & Alex Adair - Burnin’ [Premiere - Free].webm`
From log: 
`08:50:30 INFO: uname_result(system='Linux', node='lamka02sk', release='4.4.0-22-generic', version='#40-Ubuntu SMP Thu May 12 22:03:46 UTC 2016', machine='x86_64', processor='x86_64')
08:50:30 INFO: pyjam version 1.2.9
08:50:31 INFO: Generating track list with path /media/lamka02sk/silver/pyjamcsgo
08:53:09 INFO: Beginning download
08:53:09 INFO: All songs were downloaded succesfully!
08:53:19 INFO: 
08:53:19 CRITICAL: FFmpeg converter: Couldn't convert /media/lamka02sk/silver/pyjamcsgo/Steve Void & Alex Adair - Burnin’ [Premiere - Free].webm
08:53:19 CRITICAL: FFmpeg converter: Error output log
/usr/bin/ffmpeg: /tmp/_MEI9rViEe/libstdc++.so.6: version GLIBCXX_3.4.21' not found (required by /usr/lib/x86_64-linux-gnu/libjack.so.0)
/usr/bin/ffmpeg: /tmp/_MEI9rViEe/libstdc++.so.6: version GLIBCXX_3.4.21' not found (required by /usr/lib/x86_64-linux-gnu/libzmq.so.5)
/usr/bin/ffmpeg: /tmp/_MEI9rViEe/libstdc++.so.6: version GLIBCXX_3.4.21' not found (required by /usr/lib/x86_64-linux-gnu/libopencv_core.so.2.4)
/usr/bin/ffmpeg: /tmp/_MEI9rViEe/libstdc++.so.6: version GLIBCXX_3.4.21' not found (required by /usr/lib/x86_64-linux-gnu/libopencv_imgproc.so.2.4)
/usr/bin/ffmpeg: /tmp/_MEI9rViEe/libstdc++.so.6: version GLIBCXX_3.4.21' not found (required by /usr/lib/x86_64-linux-gnu/libsnappy.so.1)
/usr/bin/ffmpeg: /tmp/_MEI9rViEe/libstdc++.so.6: version GLIBCXX_3.4.21' not found (required by /usr/lib/x86_64-linux-gnu/libtbb.so.2)

08:55:33 CRITICAL: Error converting these files
/media/lamka02sk/silver/pyjamcsgo/Steve Void & Alex Adair - Burnin’ [Premiere - Free].webm
08:55:33 INFO: Songs converted with 1 error(s)
08:55:34 INFO: Generating track list with path /media/lamka02sk/silver/pyjamcsgo`

**Comment by 10se1ucgo** [comment]
It looks like you didn't compile FFmpeg correctly, it says it's missing .so dependencies

**Comment by 10se1ucgo** [comment]
Closing issue because no response. 

Try installing the `build-essentials` package.
